import { db, queryClient } from './client.js';
import { companies, type NewCompany } from './schema/companies.js';
import { users, type NewUser } from './schema/users.js';

const SEED_COMPANIES: NewCompany[] = [
  // Tier 1 - Unicorns, Scaleups & Tech Leaders HQ in Barcelona
  {
    name: 'Glovo',
    slug: 'glovo',
    website: 'https://glovoapp.com',
    careersUrl: 'https://jobs.glovoapp.com',
    atsProvider: 'greenhouse',
    atsIdentifier: 'glovo',
    atsApiEndpoint: 'https://boards-api.greenhouse.io/v1/boards/glovo/jobs',
    location: 'Barcelona, Spain',
    isBarcelonaHq: true,
    hasBarcelonaOffice: true,
    industry: 'Delivery & Quick Commerce',
    tier: 1,
    metadata: {
      description: 'Pioneering multi-category on-demand delivery platform founded in Barcelona.',
      sizeRange: '1000-5000',
      fundingStage: 'Acquired / Public (Delivery Hero)',
      techStack: ['Java', 'Kotlin', 'TypeScript', 'React', 'AWS', 'Python'],
      tags: ['Delivery', 'Scaleup', 'Logistics', 'YellowPark'],
    },
  },
  {
    name: 'Typeform',
    slug: 'typeform',
    website: 'https://www.typeform.com',
    careersUrl: 'https://www.typeform.com/careers',
    atsProvider: 'greenhouse',
    atsIdentifier: 'typeform',
    atsApiEndpoint: 'https://boards-api.greenhouse.io/v1/boards/typeform/jobs',
    location: 'Barcelona, Spain',
    isBarcelonaHq: true,
    hasBarcelonaOffice: true,
    industry: 'SaaS / Conversational AI & Forms',
    tier: 1,
    metadata: {
      description: 'Conversational interaction platform making form filling interactive and engaging.',
      sizeRange: '500-1000',
      fundingStage: 'Series C',
      techStack: ['TypeScript', 'Node.js', 'React', 'Go', 'AWS'],
      tags: ['SaaS', 'Design', 'Product', 'Poblenou'],
    },
  },
  {
    name: 'TravelPerk',
    slug: 'travelperk',
    website: 'https://www.travelperk.com',
    careersUrl: 'https://www.travelperk.com/careers',
    atsProvider: 'greenhouse',
    atsIdentifier: 'travelperk',
    atsApiEndpoint: 'https://boards-api.greenhouse.io/v1/boards/travelperk/jobs',
    location: 'Barcelona, Spain',
    isBarcelonaHq: true,
    hasBarcelonaOffice: true,
    industry: 'Travel Tech SaaS',
    tier: 1,
    metadata: {
      description: 'Next-generation all-in-one business travel management platform unicorn.',
      sizeRange: '1000-5000',
      fundingStage: 'Series D / Unicorn',
      techStack: ['Python', 'Django', 'React', 'TypeScript', 'PostgreSQL'],
      tags: ['Unicorn', 'TravelTech', 'Scaleup'],
    },
  },
  {
    name: 'Factorial',
    slug: 'factorial',
    website: 'https://factorialhr.com',
    careersUrl: 'https://factorialhr.com/careers',
    atsProvider: 'factorial',
    atsIdentifier: 'factorial',
    atsApiEndpoint: 'https://api.factorialhr.com',
    location: 'Barcelona, Spain',
    isBarcelonaHq: true,
    hasBarcelonaOffice: true,
    industry: 'HR Tech SaaS',
    tier: 1,
    metadata: {
      description: 'All-in-one HR software unicorn automating HR workflows for SMBs.',
      sizeRange: '500-1000',
      fundingStage: 'Series C / Unicorn',
      techStack: ['Ruby on Rails', 'React', 'TypeScript', 'GraphQL', 'PostgreSQL'],
      tags: ['Unicorn', 'HRTech', 'SaaS', 'Itnig'],
    },
  },
  {
    name: 'Wallapop',
    slug: 'wallapop',
    website: 'https://es.wallapop.com',
    careersUrl: 'https://jobs.wallapop.com',
    atsProvider: 'greenhouse',
    atsIdentifier: 'wallapop',
    atsApiEndpoint: 'https://boards-api.greenhouse.io/v1/boards/wallapop/jobs',
    location: 'Barcelona, Spain',
    isBarcelonaHq: true,
    hasBarcelonaOffice: true,
    industry: 'Circular Economy / Marketplace',
    tier: 1,
    metadata: {
      description: 'Leading hyper-local circular economy and secondhand goods marketplace in Southern Europe.',
      sizeRange: '200-500',
      fundingStage: 'Series G / Scaleup',
      techStack: ['Kotlin', 'Java', 'Scala', 'React', 'Python', 'Kubernetes'],
      tags: ['Marketplace', 'Mobile', 'Sustainability'],
    },
  },
  {
    name: 'Adevinta',
    slug: 'adevinta',
    website: 'https://www.adevinta.com',
    careersUrl: 'https://www.adevinta.com/careers',
    atsProvider: 'smartrecruiters',
    atsIdentifier: 'adevinta',
    atsApiEndpoint: 'https://api.smartrecruiters.com/v1/companies/adevinta/postings',
    location: 'Barcelona, Spain',
    isBarcelonaHq: true,
    hasBarcelonaOffice: true,
    industry: 'Digital Marketplaces & Classifieds',
    tier: 1,
    metadata: {
      description: 'Global digital classifieds specialist operating InfoJobs, Fotocasa, Habitaclia, and Milanuncios.',
      sizeRange: '1000-5000',
      fundingStage: 'Private Equity / Enterprise',
      techStack: ['Java', 'Node.js', 'TypeScript', 'React', 'AWS', 'Kafka'],
      tags: ['Classifieds', 'Marketplace', 'Enterprise', 'Glories'],
    },
  },
  {
    name: 'Holded',
    slug: 'holded',
    website: 'https://www.holded.com',
    careersUrl: 'https://jobs.holded.com',
    atsProvider: 'teamtailor',
    atsIdentifier: 'holded',
    atsApiEndpoint: 'https://api.teamtailor.com/v1',
    location: 'Barcelona, Spain',
    isBarcelonaHq: true,
    hasBarcelonaOffice: true,
    industry: 'Fintech & Cloud ERP',
    tier: 1,
    metadata: {
      description: 'Modern smart business management and cloud ERP platform for SMBs (part of Visma).',
      sizeRange: '200-500',
      fundingStage: 'Acquired (Visma)',
      techStack: ['Vue.js', 'Node.js', 'TypeScript', 'MongoDB', 'PostgreSQL'],
      tags: ['Fintech', 'ERP', 'SaaS', 'Visma'],
    },
  },
  {
    name: 'DocPlanner / Doctoralia',
    slug: 'docplanner',
    website: 'https://www.docplanner.com',
    careersUrl: 'https://www.docplanner.com/career',
    atsProvider: 'smartrecruiters',
    atsIdentifier: 'docplanner',
    atsApiEndpoint: 'https://api.smartrecruiters.com/v1/companies/docplanner/postings',
    location: 'Barcelona, Spain',
    isBarcelonaHq: false,
    hasBarcelonaOffice: true,
    industry: 'HealthTech / SaaS',
    tier: 1,
    metadata: {
      description: 'Leading global healthcare booking and practice management software for doctors and patients.',
      sizeRange: '1000-5000',
      fundingStage: 'Scaleup',
      techStack: ['PHP', 'Symfony', 'React', 'TypeScript', 'PostgreSQL'],
      tags: ['HealthTech', 'Doctoralia', 'Scaleup'],
    },
  },

  // Major International Tech Hubs in Barcelona
  {
    name: 'N26 (Barcelona Tech Hub)',
    slug: 'n26-barcelona',
    website: 'https://n26.com',
    careersUrl: 'https://n26.com/en-es/careers',
    atsProvider: 'greenhouse',
    atsIdentifier: 'n26',
    atsApiEndpoint: 'https://boards-api.greenhouse.io/v1/boards/n26/jobs',
    location: 'Barcelona, Spain',
    isBarcelonaHq: false,
    hasBarcelonaOffice: true,
    industry: 'Fintech / Digital Banking',
    tier: 1,
    metadata: {
      description: 'Pan-European mobile bank unicorn with a major engineering & product hub in @22 Poblenou.',
      sizeRange: '1000-5000',
      fundingStage: 'Unicorn',
      techStack: ['Java', 'Kotlin', 'Spring Boot', 'TypeScript', 'React', 'AWS'],
      tags: ['Fintech', 'Banking', 'TechHub', 'Poblenou'],
    },
  },
  {
    name: 'Revolut (Barcelona Hub)',
    slug: 'revolut-barcelona',
    website: 'https://www.revolut.com',
    careersUrl: 'https://www.revolut.com/careers',
    atsProvider: 'lever',
    atsIdentifier: 'revolut',
    atsApiEndpoint: 'https://api.lever.co/v0/postings/revolut',
    location: 'Barcelona, Spain',
    isBarcelonaHq: false,
    hasBarcelonaOffice: true,
    industry: 'Fintech / Financial SuperApp',
    tier: 1,
    metadata: {
      description: 'Global financial super app with a growing product and tech presence in Barcelona.',
      sizeRange: '5000+',
      fundingStage: 'Global Fintech Unicorn',
      techStack: ['Java', 'Python', 'React', 'TypeScript', 'GCP'],
      tags: ['Fintech', 'Scaleup', 'Global'],
    },
  },
  {
    name: 'Qonto (Barcelona Hub)',
    slug: 'qonto-barcelona',
    website: 'https://qonto.com',
    careersUrl: 'https://qonto.com/en/careers',
    atsProvider: 'greenhouse',
    atsIdentifier: 'qonto',
    atsApiEndpoint: 'https://boards-api.greenhouse.io/v1/boards/qonto/jobs',
    location: 'Barcelona, Spain',
    isBarcelonaHq: false,
    hasBarcelonaOffice: true,
    industry: 'Fintech / Business Banking',
    tier: 1,
    metadata: {
      description: 'Leading European business financial management and banking unicorn.',
      sizeRange: '1000-5000',
      fundingStage: 'Series D / Unicorn',
      techStack: ['Ruby', 'Go', 'React', 'TypeScript', 'PostgreSQL', 'Kafka'],
      tags: ['Fintech', 'B2B', 'SaaS'],
    },
  },
  {
    name: 'PayFit (Barcelona Office)',
    slug: 'payfit',
    website: 'https://payfit.com',
    careersUrl: 'https://payfit.com/careers',
    atsProvider: 'greenhouse',
    atsIdentifier: 'payfit',
    atsApiEndpoint: 'https://boards-api.greenhouse.io/v1/boards/payfit/jobs',
    location: 'Barcelona, Spain',
    isBarcelonaHq: false,
    hasBarcelonaOffice: true,
    industry: 'HR Tech & Payroll SaaS',
    tier: 1,
    metadata: {
      description: 'Cloud payroll and HR management platform for European SMBs.',
      sizeRange: '500-1000',
      fundingStage: 'Series E / Unicorn',
      techStack: ['TypeScript', 'Node.js', 'React', 'GraphQL', 'MongoDB'],
      tags: ['HRTech', 'SaaS', 'Payroll'],
    },
  },
  {
    name: 'UserTesting / UserZoom',
    slug: 'usertesting',
    website: 'https://www.usertesting.com',
    careersUrl: 'https://www.usertesting.com/about-us/careers',
    atsProvider: 'greenhouse',
    atsIdentifier: 'usertesting',
    atsApiEndpoint: 'https://boards-api.greenhouse.io/v1/boards/usertesting/jobs',
    location: 'Barcelona, Spain',
    isBarcelonaHq: false,
    hasBarcelonaOffice: true,
    industry: 'UX Research & Customer Experience SaaS',
    tier: 1,
    metadata: {
      description: 'Leader in video-based human insights and UX research (incorporating Barcelona-born UserZoom).',
      sizeRange: '1000-5000',
      fundingStage: 'Private Equity (Thoma Bravo)',
      techStack: ['Java', 'Node.js', 'TypeScript', 'Angular', 'React', 'AWS'],
      tags: ['UX', 'SaaS', 'ProductDesign', 'Research'],
    },
  },
  {
    name: 'FlixBus (Barcelona Tech Hub)',
    slug: 'flixbus-barcelona',
    website: 'https://www.flixbus.com',
    careersUrl: 'https://www.flixbus.com/company/careers',
    atsProvider: 'greenhouse',
    atsIdentifier: 'flixbus',
    atsApiEndpoint: 'https://boards-api.greenhouse.io/v1/boards/flixbus/jobs',
    location: 'Barcelona, Spain',
    isBarcelonaHq: false,
    hasBarcelonaOffice: true,
    industry: 'Mobility & Travel Tech',
    tier: 1,
    metadata: {
      description: 'Global tech-mobility powerhouse driving green intercity coach travel.',
      sizeRange: '1000-5000',
      fundingStage: 'Public / Scaleup',
      techStack: ['Java', 'Kotlin', 'TypeScript', 'React', 'AWS'],
      tags: ['TravelTech', 'Mobility', 'TechHub'],
    },
  },
  {
    name: 'Free Now',
    slug: 'free-now',
    website: 'https://www.free-now.com',
    careersUrl: 'https://www.free-now.com/careers',
    atsProvider: 'greenhouse',
    atsIdentifier: 'freenow',
    atsApiEndpoint: 'https://boards-api.greenhouse.io/v1/boards/freenow/jobs',
    location: 'Barcelona, Spain',
    isBarcelonaHq: false,
    hasBarcelonaOffice: true,
    industry: 'Urban Mobility & Ride Hailing',
    tier: 1,
    metadata: {
      description: 'Europe’s leading mobility super app joint-venture by BMW and Mercedes-Benz.',
      sizeRange: '1000-5000',
      fundingStage: 'Enterprise Joint Venture',
      techStack: ['Java', 'Kotlin', 'React Native', 'AWS', 'Kafka'],
      tags: ['Mobility', 'Transit', 'TechHub'],
    },
  },
  {
    name: 'Cabify',
    slug: 'cabify',
    website: 'https://cabify.com',
    careersUrl: 'https://cabify.careers',
    atsProvider: 'greenhouse',
    atsIdentifier: 'cabify',
    atsApiEndpoint: 'https://boards-api.greenhouse.io/v1/boards/cabify/jobs',
    location: 'Barcelona, Spain',
    isBarcelonaHq: false,
    hasBarcelonaOffice: true,
    industry: 'Mobility Tech & Logistics',
    tier: 1,
    metadata: {
      description: 'Ibero-American multi-mobility platform unicorn connecting riders, couriers, and businesses.',
      sizeRange: '1000-5000',
      fundingStage: 'Unicorn',
      techStack: ['Go', 'Elixir', 'Ruby', 'TypeScript', 'React Native', 'PostgreSQL'],
      tags: ['Mobility', 'Unicorn', 'Logistics'],
    },
  },

  // High Growth Startups & Scaleups in Barcelona (Tier 2)
  {
    name: 'Coverflex',
    slug: 'coverflex',
    website: 'https://www.coverflex.com',
    careersUrl: 'https://jobs.ashbyhq.com/coverflex',
    atsProvider: 'ashby',
    atsIdentifier: 'coverflex',
    atsApiEndpoint: 'https://api.ashbyhq.com/posting-api/job-board/coverflex',
    location: 'Barcelona, Spain',
    isBarcelonaHq: false,
    hasBarcelonaOffice: true,
    industry: 'Fintech & Employee Benefits',
    tier: 2,
    metadata: {
      description: 'Flexible compensation and employee benefits management platform.',
      sizeRange: '100-250',
      fundingStage: 'Series A',
      techStack: ['TypeScript', 'Elixir', 'React', 'PostgreSQL'],
      tags: ['Fintech', 'Benefits', 'SaaS', 'Remote-friendly'],
    },
  },
  {
    name: 'Belvo',
    slug: 'belvo',
    website: 'https://belvo.com',
    careersUrl: 'https://jobs.ashbyhq.com/belvo',
    atsProvider: 'ashby',
    atsIdentifier: 'belvo',
    atsApiEndpoint: 'https://api.ashbyhq.com/posting-api/job-board/belvo',
    location: 'Barcelona, Spain',
    isBarcelonaHq: false,
    hasBarcelonaOffice: true,
    industry: 'Open Finance & API Platform',
    tier: 2,
    metadata: {
      description: 'Leading Open Finance API platform in Latin America and Southern Europe.',
      sizeRange: '100-250',
      fundingStage: 'Series A',
      techStack: ['Python', 'Django', 'TypeScript', 'React', 'AWS', 'Docker'],
      tags: ['OpenFinance', 'API', 'Fintech'],
    },
  },
  {
    name: 'Lodgify',
    slug: 'lodgify',
    website: 'https://www.lodgify.com',
    careersUrl: 'https://lodgify.workable.com',
    atsProvider: 'workable',
    atsIdentifier: 'lodgify',
    atsApiEndpoint: 'https://apply.workable.com/api/v1/widget/accounts/lodgify',
    location: 'Barcelona, Spain',
    isBarcelonaHq: true,
    hasBarcelonaOffice: true,
    industry: 'Hospitality Tech / Vacation Rental SaaS',
    tier: 2,
    metadata: {
      description: 'All-in-one software solution for vacation rental owners and property managers.',
      sizeRange: '200-500',
      fundingStage: 'Series B',
      techStack: ['C#', '.NET Core', 'React', 'TypeScript', 'PostgreSQL', 'AWS'],
      tags: ['Hospitality', 'SaaS', 'E-commerce'],
    },
  },
  {
    name: 'Red Points',
    slug: 'redpoints',
    website: 'https://www.redpoints.com',
    careersUrl: 'https://jobs.lever.co/redpoints',
    atsProvider: 'lever',
    atsIdentifier: 'redpoints',
    atsApiEndpoint: 'https://api.lever.co/v0/postings/redpoints',
    location: 'Barcelona, Spain',
    isBarcelonaHq: true,
    hasBarcelonaOffice: true,
    industry: 'Cybersecurity / IP Protection SaaS',
    tier: 2,
    metadata: {
      description: 'Automated brand protection, anti-counterfeiting, and copyright infringement software.',
      sizeRange: '200-500',
      fundingStage: 'Series C',
      techStack: ['Python', 'TypeScript', 'React', 'PostgreSQL', 'Elasticsearch'],
      tags: ['Cybersecurity', 'IP', 'AI', 'SaaS'],
    },
  },
  {
    name: 'Kantox',
    slug: 'kantox',
    website: 'https://www.kantox.com',
    careersUrl: 'https://jobs.lever.co/kantox',
    atsProvider: 'lever',
    atsIdentifier: 'kantox',
    atsApiEndpoint: 'https://api.lever.co/v0/postings/kantox',
    location: 'Barcelona, Spain',
    isBarcelonaHq: true,
    hasBarcelonaOffice: true,
    industry: 'Fintech / FX Currency Automation',
    tier: 2,
    metadata: {
      description: 'Leading currency automation software (Currency Management Automation - CMA) (part of BNP Paribas).',
      sizeRange: '100-250',
      fundingStage: 'Acquired (BNP Paribas)',
      techStack: ['Ruby on Rails', 'React', 'TypeScript', 'PostgreSQL'],
      tags: ['Fintech', 'Forex', 'Automation'],
    },
  },
  {
    name: 'Amenitiz',
    slug: 'amenitiz',
    website: 'https://www.amenitiz.com',
    careersUrl: 'https://boards.greenhouse.io/amenitiz',
    atsProvider: 'greenhouse',
    atsIdentifier: 'amenitiz',
    atsApiEndpoint: 'https://boards-api.greenhouse.io/v1/boards/amenitiz/jobs',
    location: 'Barcelona, Spain',
    isBarcelonaHq: true,
    hasBarcelonaOffice: true,
    industry: 'Hospitality Tech SaaS',
    tier: 2,
    metadata: {
      description: 'All-in-one operating system empowering independent hoteliers across Europe.',
      sizeRange: '200-500',
      fundingStage: 'Series B',
      techStack: ['Ruby on Rails', 'React', 'TypeScript', 'PostgreSQL'],
      tags: ['Hospitality', 'SaaS', 'Scaleup'],
    },
  },
  {
    name: 'Heetch',
    slug: 'heetch',
    website: 'https://www.heetch.com',
    careersUrl: 'https://boards.greenhouse.io/heetch',
    atsProvider: 'greenhouse',
    atsIdentifier: 'heetch',
    atsApiEndpoint: 'https://boards-api.greenhouse.io/v1/boards/heetch/jobs',
    location: 'Barcelona, Spain',
    isBarcelonaHq: false,
    hasBarcelonaOffice: true,
    industry: 'Ride-Hailing & Mobility',
    tier: 2,
    metadata: {
      description: 'Friendly ride-hailing app operating in Europe and Africa with an active Barcelona dev hub.',
      sizeRange: '200-500',
      fundingStage: 'Series B',
      techStack: ['Go', 'Ruby', 'Kafka', 'React', 'PostgreSQL'],
      tags: ['Mobility', 'Transit', 'Backend'],
    },
  },
  {
    name: 'Restb.ai',
    slug: 'restbai',
    website: 'https://restb.ai',
    careersUrl: 'https://restbai.workable.com',
    atsProvider: 'workable',
    atsIdentifier: 'restbai',
    atsApiEndpoint: 'https://apply.workable.com/api/v1/widget/accounts/restbai',
    location: 'Barcelona, Spain',
    isBarcelonaHq: true,
    hasBarcelonaOffice: true,
    industry: 'Artificial Intelligence & Computer Vision',
    tier: 2,
    metadata: {
      description: 'Computer vision and multimodal AI pioneer for real estate and property insurance.',
      sizeRange: '50-100',
      fundingStage: 'Series A',
      techStack: ['Python', 'PyTorch', 'TensorFlow', 'FastAPI', 'Docker', 'AWS'],
      tags: ['AI', 'ComputerVision', 'DeepLearning', 'PropTech'],
    },
  },
  {
    name: 'Marfeel',
    slug: 'marfeel',
    website: 'https://www.marfeel.com',
    careersUrl: 'https://jobs.lever.co/marfeel',
    atsProvider: 'lever',
    atsIdentifier: 'marfeel',
    atsApiEndpoint: 'https://api.lever.co/v0/postings/marfeel',
    location: 'Barcelona, Spain',
    isBarcelonaHq: true,
    hasBarcelonaOffice: true,
    industry: 'Analytics & Publishing Tech',
    tier: 2,
    metadata: {
      description: 'Content intelligence and digital publishing analytics platform.',
      sizeRange: '100-250',
      fundingStage: 'Scaleup',
      techStack: ['Java', 'TypeScript', 'Node.js', 'React', 'BigQuery'],
      tags: ['Analytics', 'AdTech', 'Publishing'],
    },
  },
  {
    name: 'ProtoPixel',
    slug: 'protopixel',
    website: 'https://protopixel.com',
    careersUrl: 'https://protopixel.teamtailor.com',
    atsProvider: 'teamtailor',
    atsIdentifier: 'protopixel',
    atsApiEndpoint: 'https://api.teamtailor.com/v1',
    location: 'Barcelona, Spain',
    isBarcelonaHq: true,
    hasBarcelonaOffice: true,
    industry: 'Creative Tech & Smart Lighting Software',
    tier: 2,
    metadata: {
      description: 'Connected lighting platform for experiential architecture and interactive spatial design.',
      sizeRange: '20-50',
      fundingStage: 'Growth',
      techStack: ['Python', 'C++', 'TypeScript', 'React', 'WebGL'],
      tags: ['CreativeTech', 'IoT', 'Lighting', 'Design'],
    },
  },
  {
    name: 'Domestic Data Streamers',
    slug: 'domestic-data-streamers',
    website: 'https://domesticstreamers.com',
    careersUrl: 'https://domesticstreamers.com/careers',
    atsProvider: 'teamtailor',
    atsIdentifier: 'domesticdatastreamers',
    atsApiEndpoint: 'https://api.teamtailor.com/v1',
    location: 'Barcelona, Spain',
    isBarcelonaHq: true,
    hasBarcelonaOffice: true,
    industry: 'Data Experience Design & Creative AI Studio',
    tier: 2,
    metadata: {
      description: 'Creative studio transforming raw data into participatory experiences, exhibitions, and interactive storytelling.',
      sizeRange: '20-50',
      fundingStage: 'Independent Studio',
      techStack: ['TypeScript', 'Python', 'Three.js', 'Creative Coding', 'Design'],
      tags: ['DataDesign', 'CreativeCoding', 'Studio', 'Exhibition'],
    },
  },
  {
    name: 'Acid House Barcelona / Folch',
    slug: 'acid-house-barcelona',
    website: 'https://acidhousebcn.com',
    careersUrl: 'https://acidhousebcn.com',
    atsProvider: 'custom',
    atsIdentifier: 'acidhousebcn',
    atsApiEndpoint: '',
    location: 'Barcelona, Spain',
    isBarcelonaHq: true,
    hasBarcelonaOffice: true,
    industry: 'Design Innovation & Creative Business',
    tier: 2,
    metadata: {
      description: 'Creative hub and design innovation studio based in Poblenou.',
      sizeRange: '20-50',
      fundingStage: 'Independent',
      techStack: ['Design Systems', 'Next.js', 'Creative Direction'],
      tags: ['Design', 'CreativeStudio', 'Poblenou'],
    },
  },
  {
    name: 'Exoticca',
    slug: 'exoticca',
    website: 'https://www.exoticca.com',
    careersUrl: 'https://boards.greenhouse.io/exoticca',
    atsProvider: 'greenhouse',
    atsIdentifier: 'exoticca',
    atsApiEndpoint: 'https://boards-api.greenhouse.io/v1/boards/exoticca/jobs',
    location: 'Barcelona, Spain',
    isBarcelonaHq: true,
    hasBarcelonaOffice: true,
    industry: 'E-commerce & Travel Tech',
    tier: 2,
    metadata: {
      description: 'Curated long-haul luxury vacation package platform.',
      sizeRange: '200-500',
      fundingStage: 'Series C',
      techStack: ['PHP', 'Symfony', 'TypeScript', 'Vue.js', 'AWS'],
      tags: ['TravelTech', 'E-commerce', 'Scaleup'],
    },
  },
  {
    name: 'Mitiga Solutions',
    slug: 'mitiga-solutions',
    website: 'https://www.mitigasolutions.com',
    careersUrl: 'https://jobs.lever.co/mitigasolutions',
    atsProvider: 'lever',
    atsIdentifier: 'mitigasolutions',
    atsApiEndpoint: 'https://api.lever.co/v0/postings/mitigasolutions',
    location: 'Barcelona, Spain',
    isBarcelonaHq: true,
    hasBarcelonaOffice: true,
    industry: 'ClimateTech & GeoAI Supercomputing',
    tier: 2,
    metadata: {
      description: 'Climate risk intelligence and high-performance computing (HPC) spun out of Barcelona Supercomputing Center (BSC).',
      sizeRange: '50-100',
      fundingStage: 'Series A',
      techStack: ['Python', 'Fortran', 'C++', 'HPC', 'TypeScript', 'React'],
      tags: ['ClimateTech', 'GeoAI', 'BSC', 'DeepTech'],
    },
  },
];

const DEFAULT_SEED_USER: NewUser = {
  telegramId: 'ADMIN_TEST_USER_1',
  telegramUsername: 'bcn_intern_hunter',
  fullName: 'Barcelona Candidate',
  email: 'intern@bcn-tech.dev',
  profile: {
    targetRoles: [
      'Software Engineering Intern',
      'Frontend Intern',
      'Full Stack Intern',
      'Backend Intern',
      'AI/ML Engineering Intern',
      'Product Design Intern',
    ],
    disciplines: ['Software Engineering', 'Product Design'],
    skills: [
      'TypeScript',
      'JavaScript',
      'React',
      'Next.js',
      'Node.js',
      'Python',
      'PostgreSQL',
      'Tailwind CSS',
      'Git',
      'Docker',
    ],
    languages: ['English', 'Spanish', 'Catalan'],
    preferredLocations: ['Barcelona', 'Sant Cugat', 'Remote'],
    contractTypes: ['Any Contract'],
    remotePreference: 'hybrid',
    maxCommuteMinutes: 45,
    educationLevel: "Bachelor's Degree / Student",
    fieldOfStudy: 'Computer Science / Software Engineering / Interaction Design',
    graduationYear: 2026,
    visaRequired: false,
    bio: 'Passionate junior developer and design enthusiast looking for cutting-edge software and design internships in Barcelona tech companies.',
  },
  preferences: {
    notificationFrequency: 'instant',
    minScoreThreshold: 0.60,
    telegramNotificationsEnabled: true,
    hardFilters: {
      mustMatchPreferredLocations: true,
      requirePaidOnly: false,
    },
  },
  isActive: true,
  isAdmin: true,
};

export async function seed() {
  console.log('🌱 Starting Barcelona Internship Bot Database Seeding...');

  try {
    // 1. Seed companies
    console.log(`📦 Seeding ${SEED_COMPANIES.length} top Barcelona tech companies & scaleups...`);
    let insertedCompanies = 0;
    for (const company of SEED_COMPANIES) {
      await db
        .insert(companies)
        .values(company)
        .onConflictDoUpdate({
          target: companies.slug,
          set: {
            name: company.name,
            website: company.website,
            careersUrl: company.careersUrl,
            atsProvider: company.atsProvider,
            atsIdentifier: company.atsIdentifier,
            atsApiEndpoint: company.atsApiEndpoint,
            location: company.location,
            isBarcelonaHq: company.isBarcelonaHq,
            hasBarcelonaOffice: company.hasBarcelonaOffice,
            industry: company.industry,
            tier: company.tier,
            metadata: company.metadata,
            isActive: company.isActive,
            updatedAt: new Date(),
          },
        });
      insertedCompanies++;
    }
    console.log(`✅ Successfully seeded/updated ${insertedCompanies} companies.`);

    // 2. Seed default user profile
    console.log('👤 Seeding default admin user profile template...');
    await db
      .insert(users)
      .values(DEFAULT_SEED_USER)
      .onConflictDoUpdate({
        target: users.telegramId,
        set: {
          fullName: DEFAULT_SEED_USER.fullName,
          telegramUsername: DEFAULT_SEED_USER.telegramUsername,
          profile: DEFAULT_SEED_USER.profile,
          preferences: DEFAULT_SEED_USER.preferences,
          isActive: true,
          isAdmin: true,
          updatedAt: new Date(),
        },
      });
    console.log('✅ Successfully seeded default user template.');

    console.log('🎉 Seeding completed successfully!');
  } catch (error) {
    console.error('❌ Error while seeding database:', error);
    process.exit(1);
  } finally {
    await queryClient.end();
  }
}

// Execute directly if run via tsx
if (import.meta.url.endsWith(process.argv[1] ?? '')) {
  seed();
}
